### ISSUE TITLE
安卓客户端无法接收内容,仅能接收标题!!!

### ISSUE THREAD

**Issue by Jonnyan404** [kooritea/mpush#2]
### 版本信息

mpush-server:2.1.2
mpush-android-client:2.0.2

###  问题
1. 无法接收内容,仅能接收标题?
2. 标题和内容不能自动转码接收中文?
3. app 删除功能有bug,删除后,界面不刷新.(小米,miui12)

**Comment by Jonnyan404** [comment]
emmm....非1.0的版本,我都试过来,,,,2.0版本,除了能显示英文标题,别的啥也干不了~~~~

**Comment by kooritea** [comment]
1. 这个我在这里测试没有问题，会不会是你的字段用错了，标题是text内容是desp
```bash
curl http://127.0.0.1:9093/test.send\?text\=%E6%B5%8B%E8%AF%95\&desp\=%E6%B5%8B%E8%AF%95
```
2. 不知道你说的转码是不是指encodeURI/decodeURI，我用的是js的方法这应该不会出问题
估计是你直接在命令行curl里面使用了中文，curl命令行不会对urlquery转码的，请测试`%E6%B5%8B%E8%AF%95`
3. 抱歉，安卓客户端年久失修没有对7.1以上的系统进行支持，7.1以上的安卓版本建议用pwa版，pwa版对FCM支持友好比较省电

**Comment by Jonnyan404** [comment]
> 1. 这个我在这里测试没有问题，会不会是你的字段用错了，标题是text内容是desp
> 
> ```shell
> curl http://127.0.0.1:9093/test.send\?text\=%E6%B5%8B%E8%AF%95\&desp\=%E6%B5%8B%E8%AF%95
> ```
> 
> 1. 不知道你说的转码是不是指encodeURI/decodeURI，我用的是js的方法这应该不会出问题
>    估计是你直接在命令行curl里面使用了中文，curl命令行不会对urlquery转码的，请测试`%E6%B5%8B%E8%AF%95`
> 2. 抱歉，安卓客户端年久失修没有对7.1以上的系统进行支持，7.1以上的安卓版本建议用pwa版，pwa版对FCM支持友好比较省电

- 字段没漏,看来是 安卓 版本太高了.刚看了下,已经Android 10 了...
- pwa是个网页?感觉没有 app 方便.

**Comment by kooritea** [comment]
使用chrome浏览器打开可以添加到桌面
不过确实是不去原生app方便，可是我不太熟悉安卓的开发只能等哪位大佬来了😂

**Comment by Jonnyan404** [comment]
> 使用chrome浏览器打开可以添加到桌面
> 不过确实是不去原生app方便，可是我不太熟悉安卓的开发只能等哪位大佬来了😂

可以看下 uni-app,它可以生成多端app.

**Comment by Jonnyan404** [comment]
@kooritea 好吧,应该是curl命令的锅,我再浏览器地址栏输入就正常了.

**Comment by Jonnyan404** [comment]
@kooritea 我发现通知会在几秒之后自动消失,可以让它一直展示在状态栏吗?
---
这个是miui的机制,我调整后好了.

**Comment by kooritea** [comment]
这个是当应用在前台的时候考虑到通知已读才去掉通知的
现在没有设置可以改这个…

**Comment by Jonnyan404** [comment]
> 这个是当应用在前台的时候考虑到通知已读才去掉通知的
> 现在没有设置可以改这个…

嗯嗯,好的.谢谢解答
